dist: trusty
language: java
jdk:
  - oraclejdk8
install: 
  - mvn clean package org.apache.maven.plugins:maven-deploy-plugin:2.8:deploy --settings deploy.settings.xml -Dmaven.test.skip=true -DdeployAtEnd=true -X

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
  - secure: "hqV8skr8j/LVLnMWhQoDowKaKDx1RmXAc85hDLRf1OecXFMAej5cZXEB/sotBCQ147ujwbI6kBSOShT3XrzHSsrHLHa9M1uHSKFaTvBUBUGD/M1zH8NgZnOMW208r5pT166V0lQjKd0Lgx3qOircuIkkK5RWKmTCkMzC9VCfy2w="
  - secure: "i/kFabkQTREcXI8t2LR8Gs7LoN5V31LHbYG8LxqLxAx/11YUgDSGia3NxL6W3V8nk+hfWV5DwcdbA08QLs2YIMFyzg5cQ6y7LTpV42LrD9f8uwtf9mKtGT7FCBR0z3aWVJuwWXUTeyw4CgcRyP2AYQya266/p767VRpgE+l/+Vs="

cache:
  directories:
  - $HOME/.m2
