dist: trusty
language: java
jdk:
- oraclejdk8
install:
- mvn clean test
deploy:
  provider: script
  script: mvn deploy -s deploy.settings.xml -Dmaven.test.skip=true -DdeployAtEnd=true
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: lX51N3XbkyBIyVba/3zmZsVpmbXze4spJhrvszaMJQ4PUyIzXqH6GfgKYpRT6nM5BWoXpV3D8ReI8Cg0ACl8d4ZhaSSPkb92aROhSZdaiD/XAqkL7V7XI3oWhGIvHExSczd4J8wnurx+vAlwAMRjg9fQrwhY6gR8Ok3dF4XstHE=
  - secure: AO6x+I4Ju/TzkxccyM7vyaxjM+uHnYYUPnWNKZ6Wuc+KUXyDhA9C8joAnPN4o2IxzhjR6lirRCkZl0NAjKSUMkoE5CYhC2OJ35Al6es0Isd/1noqlOkA+EzW12o/5+veniB0IL79a048X6+QOPszW7z4CJ4K4J4QGHUq7lSfsEM=
