package com.abstratt.kirra;

/**
 * Represents a property.
 */
public class Property extends DataElement {

    private static final long serialVersionUID = 1;

    protected boolean unique;

    public Property() {
    }

    /**
     * An auto-generated property has its value automatically assigned.
     */
    public boolean isAutoGenerated() {
        return isUnique() && !isInitializable() && !isEditable();
    }

    /**
     * A unique property does not allow duplicated values.
     */
    public boolean isUnique() {
        return unique;
    }

    public void setUnique(boolean unique) {
        this.unique = unique;
    }
}