package com.abstratt.kirra;

/**
 * Represents a property.
 */
public class Property extends DataElement {

    private static final long serialVersionUID = 1;

    protected boolean unique;
    protected Object defaultValue;
    protected boolean mnemonic;

	protected boolean autoGenerated;

    public Property() {
    }
    
    public boolean isMnemonic() {
		return mnemonic;
	}
    public void setMnemonic(boolean mnemonic) {
		this.mnemonic = mnemonic;
	}

    /**
     * An auto-generated property has its value automatically assigned.
     */
    public boolean isAutoGenerated() {
		return autoGenerated;
    }
    
    public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

    /**
     * A unique property does not allow duplicated values.
     */
    public boolean isUnique() {
        return unique;
    }

    public void setUnique(boolean unique) {
        this.unique = unique;
    }
    
    public Object getDefaultValue() {
        return defaultValue;
    }
    
    public void setDefaultValue(Object value) {
        this.defaultValue = value;
    }
}